export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA2MDU2NjEwLCJleHAiOjE3MDYwNTg0MTAsImF1ZCI6InVzZXJzIiwiaXNzIjoiZm9yZ2V0Iiwic3ViIjoiMSJ9.dHWMUh-8uTt1O_YlJedB5aao-SdVhnfUf8mXYyzrkAg';
